/*
 * This file is generated by jOOQ.
 */
package eu.dissco.virtualcollectionservice.database.jooq;


import eu.dissco.virtualcollectionservice.database.jooq.tables.VirtualCollection;
import eu.dissco.virtualcollectionservice.database.jooq.tables.records.VirtualCollectionRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<VirtualCollectionRecord> VIRTUAL_COLLECTION_PKEY = Internal.createUniqueKey(VirtualCollection.VIRTUAL_COLLECTION, DSL.name("virtual_collection_pkey"), new TableField[] { VirtualCollection.VIRTUAL_COLLECTION.ID }, true);
}
