/*
 * This file is generated by jOOQ.
 */
package eu.dissco.virtualcollectionservice.database.jooq;


import eu.dissco.virtualcollectionservice.database.jooq.tables.VirtualCollection;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.virtual_collection</code>.
     */
    public static final VirtualCollection VIRTUAL_COLLECTION = VirtualCollection.VIRTUAL_COLLECTION;
}
